# This is a basic workflow to help you get started with Actions

name: CI/CD dev

on:
  push:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml
  publish:
    uses: ./.github/workflows/publish_docker.yml
    needs: test
    with:
      tag: dev-latest